pymisp/api.py
Si cela te semble intéréssant d'ajouter ces deux fonctions :)
=> Add 2 download functions of suricata rules events

examples/copy_list.py, pymisp/api.py
- input for add_event() and update_event() can now be a JSON object, JSON string, XML
=> API made a bit more flexible with input data

examples/get_network_activity.py
- get event data for event with “—event X”
- get netflow filter with “—netflow”
simple host X or host X
=> Add netflow filter output

examples/get.py
This will allow get.py to create a JSON object that can be digested by up.py
=> Dump the entire event including the 'Event' container element

pymisp/api.py
Hi
I added the missing types like email-src etc., since we need some of them.
Maybe you want to add them too?
Cheers
grolinet
=> Added missing types

pymisp/api.py
I added some helper methods. I hardcoded most of the category-attributes since the fields are only valid for one specific category.
cheers
=> Helper methods added

tests/test.py
=> Print the event so we can see what travis is trying to compare against

examples/last.py
Fix a KeyError when no results were found for the specified time period.
=> Fix KeyError when no results in time period

examples/get.py, examples/last.py, examples/searchall.py, examples/upload.py, examples/yara.py
Think that makes sense to use the config value
=> respect misp_verifycert in some tests

examples/feed-generator/generate.py
Prevent failing when f.e. an event does not have a tag.
=> Check if objectType exists in event

pymisp/api.py
Ability to search event index, bringing back Event and Tags, using filter to search.
Converts list to dict due to difference in response. Requires import of urllib.quote module. Also made Python 3 compatible.
=> Search Event Index

examples/ioc-2-misp/README.md, examples/ioc-2-misp/ioc2misp.py, examples/ioc-2-misp/keys.py.sample, examples/ioc-2-misp/taxonomy.csv
With this script, you can push an IOC to your misp instance.
Take a look in the keys.py for sample mapping.
=> import ioc with python

examples/et2misp.py
Thanks to https://github.com/MISP/PyMISP/pull/25 we can now update multiple attributes at once. This significantly speeds up the et2misp script.
=> Speed up et2misp

examples/make_neo4j.py, pymisp/__init__.py, pymisp/api.py, pymisp/mispevent.py, pymisp/tools/neo4j.py, pymisp/tools/openioc.py, pymisp/tools/stix.py
Add some tools, not needed for PyMISP itself but add some interesting features.
=> [WIP] Tooling

pymisp/tools/stix.py
Because we already had one!
it's just sneaky
very sneak
=> Use convert's load_stix method

pymisp/api.py
Tested successfully with the sighting tools. Works only with Python 3 ;-)
=> Errorhandling2

examples/misp2clamav.py
Usage: misp2clamav.py > /var/lib/clamav/misp.hdb
=> Convert MISP file hashes to ClamAV hdb file

examples/fetch_events_feed.py, pymisp/api.py
Hi guys,
I was looking for a way to script in order to fetch all events from feed automatically. It seems there is no function to do this so i submit you this feature to allow automatic pull.
Do not hesitate to modify it of course.
CheYen
=> Automation for fetching all events from a feed

pymisp/api.py
Missing %s in logger.debug call lead to error.
=> Fix missing %s in debug

examples/del.py
=> use misp_verifycert

examples/suricata_search/README.md, examples/suricata_search/suricata_search.py
A multi-threaded Suricata search code version, fetching ids rules based on parameters and terms.
=> multi-threaded suricata search
